name: Bundle and Create Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Bundle resotool
        if: matrix.os == 'macos-latest'
        run: cargo xtask bundle-universal resotool --release
      - name: Bundle resotool
        if: matrix.os != 'macos-latest'
        run: cargo xtask bundle resotool --release
      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resotool.vst3${{ matrix.os }}
          path: ./target/bundled/Resotool.vst3
